const constants = {
	RANDOM_HERO: 'RANDOM_HERO',
	SET_FRACTION: 'SET_FRACTION',
	SET_HEROCLASS: 'SET_HEROCLASS',
	SET_SKINTONE: 'SET_SKINTONE',
	SET_HAIRCOLOR: 'SET_HAIRCOLOR',
	SET_HAIRSTYLE: 'SET_HAIRSTYLE',
	SET_FACEHAIR: 'SET_FACEHAIR',
	SET_CHARNAME: 'SET_CHARNAME',

	SHOW_FINAL_FORM: 'SHOW_FINAL_FORM',
	HIDE_FINAL_FORM: 'HIDE_FINAL_FORM',
	CLOSE_MODULE: 'CLOSE_MODULE'
};
export default constants;
