const constants = {
	RANDOM_HERO: 'RANDOM_HERO',
	SET_FRACTION: 'SET_FRACTION',
	SET_SKINTONE: 'SET_SKINTONE',
	SET_HAIRCOLOR: 'SET_HAIRCOLOR',
	SET_HAIRSTYLE: 'SET_HAIRSTYLE',
	SET_FACEHAIR: 'SET_FACEHAIR'
};
export default constants;
